[package]
name = "shared"
version = "0.1.0"
authors = ["Lucas Poffo <ltkpoffo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
renet = { path = "../../renet" }
derive = { path = "../derive" }
macroquad = { version = "=0.3.0-alpha.14", features = [ "log-impl" ] }
serde = "1"
glam = { version = "0.10", features = [ "serde" ] }
shipyard = { git = "https://github.com/leudz/shipyard.git", rev = "a87e59e441d938bd7dc18bebf97456eff8707484", features = [ "serde1" ] }
